apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tb2hhbWVkYXplZW0wMTc0OjxkYl9wYXNzd29yZD5AY2x1c3RlcjAuMW1jMHBnaC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  PAYPAL_CLIENT_ID: QVF3YVBCUTRKZWRtV2diRExialFrMDQtN0ktN0xZZ2ZlQjRmWTVKc1NXZDAxdUxJUXVhc2dRSS1ZVFRiNm55WWpnRW5LOWw3dVhyNkxvOXY=

